backend:
  name: github
  # change repo to your git repository url
  repo: aranscope/sweptawaybath.com

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Site-Wide Settings
    files:
      - name: personal-details
        label: Personal details (name, profile picture etc.)
        file: _data/personal/personal.json
        fields:
          - widget: string
            name: first-name
            label: First Name
            required: true
          - widget: object
            name: profile-image
            label: Profile Image
            fields:
              - widget: image
                name: image
                label: Image
                required: false
                media_library:
                  config:
                    multiple: false
              - widget: string
                name: alt
                label: Alt Text
                required: false
      - name: metadata
        label: Metadata (Title etc.)
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title (in header, visible)
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: string
            name: google-site-verification
            label: Google site verification token
            required: false
          - widget: string
            name: defaultTitle
            label: Default page title
          - widget: string
            name: titleTemplate
            label: Title template
          - widget: text
            name: defaultDescription
            label: Default page description
          - widget: image
            name: defaultImage
            label: Default page image

  - name: pages
    label: Pages
    files:
      - name: reviews
        label: Reviews
        file: _data/pages/reviews-page/reviews.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: string
                name: title
                label: Text
                required: true
              - widget: image
                name: background_image
                label: Background Image
                required: true
                media_library:
                  config:
                    multiple: false
                hint: Use a high resolution image, as this takes up the full width of the screen
      - name: book
        label: Book
        file: _data/pages/book-page/book.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: string
                name: title
                label: Text
                required: true
              - widget: image
                name: background_image
                label: Background Image
                required: true
                media_library:
                  config:
                    multiple: false
                hint: Use a high resolution image, as this takes up the full width of the screen

      - name: blog
        label: Blog
        file: _data/pages/blog-page/blog.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: string
                name: title
                label: Text
                required: true
              - widget: image
                name: background_image
                label: Background Image
                required: true
                media_library:
                  config:
                    multiple: false
                hint: Use a high resolution image, as this takes up the full width of the screen

      - name: prices
        label: Prices
        file: _data/pages/prices-page/prices.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: string
                name: title
                label: Text
                required: true
              - widget: image
                name: background_image
                label: Background Image
                required: true
                media_library:
                  config:
                    multiple: false
                hint: Use a high resolution image, as this takes up the full width of the screen
          - widget: object
            name: prices
            label: Prices
            fields:
              - widget: object
                name: regular-sweep
                label: A single, regular sweep
                fields:
                  - widget: string
                    name: title
                    label: Title
                  - widget: text
                    name: description
                    label: Description
                  - widget: number
                    name: price
                    label: £ Price
                    hint: How much should a single sweep cost?
                    min: 0
                    step: 5
                min: 0
                step: 5
              - widget: list
                name: everything-else-paid
                label: The other paid stuff
                hint: The list of everything else that is paid
                fields:
                  - widget: string
                    name: title
                    label: Title
                  - widget: text
                    name: description
                    label: Description
                  - widget: select
                    name: price-type
                    label: Price type
                    options:
                      - value: per-chimney
                        label: Per Chimney
                      - value: per-job
                        label: Per Job
                      - value: per-hour
                        label: Per Hour
                  - widget: number
                    name: price
                    label: £ Price
                    hint: How much should this item cost?
                    min: 0
                    step: 5
              - widget: list
                name: everything-else-free
                label: The free stuff
                hint: The list of everything that is free
                fields:
                  - widget: string
                    name: title
                    label: Title
                  - widget: text
                    name: description
                    label: Description
                  - widget: boolean
                    name: new
                    label: Is this a new free thing?
                    default: false

      - name: home
        label: Home
        file: _data/pages/home-page/home.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: object
                name: alert
                label: Alert
                fields:
                  - widget: boolean
                    name: enabled
                    label: Enabled
                    hint: Should the alert show up at all?
                  - widget: string
                    name: badge
                    label: Badge
                  - widget: string
                    name: text
                    label: Text
                  - widget: string
                    name: link
                    label: Link
                    hint: Link to another page on the site
              - widget: image
                name: background_image
                label: Background Image
                required: true
                media_library:
                  config:
                    multiple: false
                hint: Use a high resolution image, as this takes up the full width of the screen

          - widget: object
            name: body
            label: Body
            fields:
              - widget: list
                name: sections
                label: sections
                minimize_collapsed: true
                fields:
                  - widget: object
                    name: left
                    label: Left Side
                    fields:
                      - widget: string
                        name: title
                        label: Title
                        required: true
                      - widget: text
                        name: text
                        label: Text
                        required: false
                      - widget: boolean
                        name: include_coverage_map
                        label: Include coverage map?
                        default: false
                  - widget: object
                    name: right
                    label: Right Side
                    fields:
                      - widget: string
                        name: title
                        label: Title
                        required: true
                      - widget: text
                        name: text
                        label: Text
                        required: false
                      - widget: boolean
                        name: include_booking_button
                        label: Include booking button?
                        default: false
                      - widget: boolean
                        name: include_coverage_map
                        label: Include coverage map?
                        default: false
      - name: blog
        label: Blog
        file: _data/pages/blog-page/blog.json
        create: true
        fields:
          - widget: object
            name: metadata
            label: Metadata
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: text
                name: description
                label: Description
                required: true
              - widget: image
                name: image
                label: Image
          - widget: object
            name: header
            label: Header
            fields:
              - widget: string
                name: title
                label: Title
                required: true

  - name: blog_categories
    label: Blog Categories
    folder: _data/blog-categories
    extension: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - widget: string
        name: category
        label: Category Name

  - name: blog
    label: Blog posts
    label_singular: blog post
    folder: _data/blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: BlogPost,
        }
      - name: category
        label: Category
        widget: relation
        collection: blog_categories
        searchFields: [category]
        valueField: category
      - name: path
        label: Path
        widget: string
        pattern: [/]
        hint: "Path must start with /"
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }

  - name: testimonials
    label: Customer testimonials
    label_singular: customer testimonial
    folder: _data/testimonials
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - label: When did the customer leave the review?
        name: date
        widget: datetime
        hint: If you don't know, guess, or leave it blank
      - label: What did the customer say?
        name: body
        widget: markdown
        required: true
      - label: What is the customer's name?
        name: customer_name
        widget: string
        required: true
      - label: Link to the review
        name: link
        widget: string
        hint: e.g. Google reviews, Yahoo etc. If there isn't one, leave it blank
      - label: Feature on home page?
        name: featured
        widget: boolean
        default: false
        hint: It's best to feature short reviews e.g. one sentence, so they don't take up too much space on the home page
      - label: How many stars (0-5)?
        name: stars
        widget: number
        min: 0
        max: 5